{{- if .Values.alerting.enabled -}}


# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: application-alerts
# spec:
#   groups:
#   - name: application
#     rules:
#     - alert: HighErrorRate
#       expr: |
#         sum(rate(http_requests_total{status=~"5.*"}[1m])) 
#         / 
#         sum(rate(http_requests_total[1m])) > 0.01
#       for: 1m
#       labels:
#         severity: critical
#       annotations:
#         summary: High error rate detected
        
#     - alert: HighLatency
#       expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m])) > 1
#       for: 1m
#       labels:
#         severity: warning
#       annotations:
#         summary: High latency detected
        
#     - alert: HighRequestVolume
#       expr: sum(rate(http_requests_total[1m])) > 100
#       for: 1m
#       labels:
#         severity: warning
#       annotations:
#         summary: High request volume detected
{{- end }}