---
apiVersion: v2
name: sample-app
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies: 
  - name: kafka
    condition: kafka.enabled
    version: ~31.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: ~17.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    condition: postgresql.enabled
    version: ~12.0.0
    repository: https://charts.bitnami.com/bitnami
